nodeLinker: node-modules
enableGlobalCache: false

packageExtensions:
  "@heroui/alert@*":
    dependencies:
      framer-motion: "12.16.0"
  "@heroui/aria-utils@*":
    dependencies:
      framer-motion: "12.16.0"
  "@heroui/drawer@*":
    dependencies:
      framer-motion: "12.16.0"
  "@heroui/number-input@*":
    dependencies:
      framer-motion: "12.16.0"
  "@heroui/slider@*":
    dependencies:
      framer-motion: "12.16.0"
  "@heroui/spinner@*":
    dependencies:
      framer-motion: "12.16.0"
  "@heroui/system@*":
    dependencies:
      "@heroui/theme": "2.4.16"
      tailwindcss: "3.4.17"
  "@heroui/react@*":
    dependencies:
      tailwindcss: "3.4.17"
  "@heroui/use-aria-accordion@*":
    dependencies:
      react-dom: "18.3.1"
  "@heroui/use-aria-button@*":
    dependencies:
      react-dom: "18.3.1"
  "@heroui/use-aria-link@*":
    dependencies:
      react-dom: "18.3.1"
  "@heroui/use-disclosure@*":
    dependencies:
      react-dom: "18.3.1"
  "@heroui/use-draggable@*":
    dependencies:
      react-dom: "18.3.1"
  "@heroui/use-intersection-observer@*":
    dependencies:
      react-dom: "18.3.1"
  "@heroui/use-pagination@*":
    dependencies:
      react-dom: "18.3.1"
  "@statelyai/inspect@*":
    dependencies:
      ws: "8.18.2"
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: "5.8.3"
